services:
  app:
    container_name: schemify-nestjs
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - mongo
    ports:
      - '${APP_PORT}:3000'
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_URL: ${POSTGRES_URL}
      MONGO_URI: ${MONGO_URI}
      APP_PORT: ${APP_PORT}
    volumes:
      - ./logs:/home/node/app/logs
    networks:
      - schemify-networks

  postgres:
    image: postgres:15
    container_name: schemify-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - schemify-networks

  mongo:
    image: mongo:6
    container_name: schemify-mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongodata:/data/db
    networks:
      - schemify-networks

networks:
  schemify-networks:
    driver: bridge

volumes:
  pgdata:
    driver: local
  mongodata:
    driver: local
